#!/bin/sh /etc/rc.common

START=99
STOP=90
USE_PROCD=1

start_service() {
    procd_open_instance picoclaw
    procd_set_param command /usr/bin/picoclaw gateway
    procd_set_param env HOME=/root
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    killall picoclaw 2>/dev/null
}

service_triggers() {
    procd_add_reload_trigger "picoclaw"
}
