#!/bin/sh

image_name=`uci get typecho.@main[0].image_name 2>/dev/null`

if [ "$image_name" == "typechoinc/pms-docker:latest" -a "`uname -m`" != "x86_64" ]; then
    uci -q batch <<-EOF >/dev/null
        set typecho.@main[0].image_name=""
        commit typecho
EOF
fi
exit 0
