#!/bin/sh

image_name=`uci get arcadia.@arcadia[0].image 2>/dev/null`

if [ "$image_name" == "default" ]; then
    uci -q batch <<-EOF >/dev/null
        delete arcadia.@arcadia[0].image
        commit arcadia
EOF
fi
exit 0
