

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nextcloud
PKG_VERSION:=1.0.0
PKG_RELEASE:=20210912

LUCI_TITLE:=LuCI support for nextcloud
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+docker

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


