

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-jellyfin
PKG_VERSION:=1.0.1
PKG_RELEASE:=20211014

LUCI_TITLE:=LuCI support for jellyfin
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+docker +luci-app-dockerman

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


