#!/bin/sh

image_name=`uci get feishuvpn.@main[0].image_name 2>/dev/null`

if [ "$image_name" == "feishuvpninc/pms-docker:latest" -a "`uname -m`" != "x86_64" ]; then
    uci -q batch <<-EOF >/dev/null
        set feishuvpn.@main[0].image_name=""
        commit feishuvpn
EOF
fi
exit 0
