include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Qiyou Game Booster
LUCI_DESCRIPTION:=provides Web UI to Qiyou Game Booster.
LUCI_DEPENDS:=+qiyougamebooster
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-qiyougamebooster
PKG_VERSION:=1.2.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
